apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "deltalake.configMap" . }}
  labels:
    {{- include "deltalake.labels" . | nindent 4 }}
data:
  thrift-server-config.yaml: | 
    sparkConf:
      master: {{ .Values.sparkConf.master}}
      props:
      {{- range $key, $value := .Values.sparkConf.props }}
        - {{ $key }}: {{ $value }}
      {{- end}}