{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "deltalake.serviceAccountName" . }}
  labels:
    {{- include "deltalake.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: ServiceAccount
  name: {{ include "deltalake.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}