apiVersion: v1
kind: Service
metadata:
  name: {{ include "deltalake.fullname" . }}
  labels:
    {{- include "deltalake.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 4040
      targetPort: 4040
      protocol: TCP
  selector:
    {{- include "deltalake.selectorLabels" . | nindent 4 }}